#!/usr/bin/env bash
#
# gum uninstaller - Git User Manager
#

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m'

GUM_INSTALL_DIR="${GUM_INSTALL_DIR:-$HOME/.gum}"

echo ""
echo -e "${BOLD}${YELLOW}  Uninstalling gum (Git User Manager)...${NC}"
echo -e "${DIM}  ─────────────────────────────────────────${NC}"
echo ""

# Check if profiles exist
if [[ -d "$GUM_INSTALL_DIR/profiles" ]]; then
    local_profiles=$(ls "$GUM_INSTALL_DIR/profiles"/*.conf 2>/dev/null | wc -l | tr -d ' ')
    if [[ "$local_profiles" -gt 0 ]]; then
        echo -e "  ${YELLOW}⚠ You have ${local_profiles} profile(s) saved.${NC}"
        read -p "  Delete all profiles and SSH keys managed by gum? [y/N]: " delete_profiles
        if [[ "$delete_profiles" == "y" || "$delete_profiles" == "Y" ]]; then
            # Remove SSH keys generated by gum
            for conf in "$GUM_INSTALL_DIR/profiles"/*.conf; do
                if [[ -f "$conf" ]]; then
                    ssh_key=$(grep "^GUM_SSH_KEY=" "$conf" | cut -d'=' -f2- | tr -d '"')
                    ssh_key="${ssh_key/#\~/$HOME}"
                    if [[ "$ssh_key" == *"gum_"* && -f "$ssh_key" ]]; then
                        rm -f "$ssh_key" "${ssh_key}.pub"
                        echo -e "  ${DIM}Deleted: ${ssh_key}${NC}"
                    fi
                fi
            done
        fi
    fi
fi

# Remove SSH config blocks managed by gum
SSH_CONFIG="$HOME/.ssh/config"
if [[ -f "$SSH_CONFIG" ]]; then
    if grep -q "gum managed:" "$SSH_CONFIG" 2>/dev/null; then
        if [[ "$(uname)" == "Darwin" ]]; then
            sed -i '' '/# >>> gum managed:/,/# <<< gum managed:/d' "$SSH_CONFIG"
        else
            sed -i '/# >>> gum managed:/,/# <<< gum managed:/d' "$SSH_CONFIG"
        fi
        echo -e "  ${GREEN}✓${NC} Cleaned SSH config entries"
    fi
fi

# Remove gum directory
if [[ -d "$GUM_INSTALL_DIR" ]]; then
    rm -rf "$GUM_INSTALL_DIR"
    echo -e "  ${GREEN}✓${NC} Removed ${GUM_INSTALL_DIR}"
fi

# Remove PATH from shell config
SHELL_NAME=$(basename "$SHELL")
SHELL_CONFIG=""

case "$SHELL_NAME" in
    zsh)
        SHELL_CONFIG="$HOME/.zshrc"
        ;;
    bash)
        if [[ -f "$HOME/.bash_profile" ]]; then
            SHELL_CONFIG="$HOME/.bash_profile"
        else
            SHELL_CONFIG="$HOME/.bashrc"
        fi
        ;;
    *)
        SHELL_CONFIG="$HOME/.profile"
        ;;
esac

if [[ -f "$SHELL_CONFIG" ]] && grep -q "# gum (Git User Manager)" "$SHELL_CONFIG" 2>/dev/null; then
    if [[ "$(uname)" == "Darwin" ]]; then
        sed -i '' '/# gum (Git User Manager)/d' "$SHELL_CONFIG"
        sed -i '' '/\$HOME\/.gum\/bin/d' "$SHELL_CONFIG"
    else
        sed -i '/# gum (Git User Manager)/d' "$SHELL_CONFIG"
        sed -i '/\$HOME\/.gum\/bin/d' "$SHELL_CONFIG"
    fi
    echo -e "  ${GREEN}✓${NC} Removed PATH from ${SHELL_CONFIG}"
fi

echo ""
echo -e "${GREEN}  ✓ gum has been uninstalled.${NC}"
echo ""
